version: '3.9'

services:
  redis-server:
    image: redis:latest
    container_name: social_media_redis_server
    ports:
      - "6379:6379"
    volumes:
      - /home/Docker/redis/social_media:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"] 

volumes:
  redis_data:
    driver: local
